services:
  db:
    image: postgres:16-alpine3.20
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_PASSWORD=root
  
  pgadmin:
    image: dpage/pgadmin4:8.11.0
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@user.com
      - PGADMIN_DEFAULT_PASSWORD=secret
    depends_on:
      - db